services:
  mongo:
    image: mongo:7
    container_name: overseas-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: overseas-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/overseas
      JWT_SECRET: overseas_secret_key
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: overseas-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo_data: